---
- hosts: '{{ target }}'
  gather_facts: true
  become: true
  vars_files:
  - '{{ user_file }}'
  roles:
    - setup
    - install_monitoring
    - install_zsh
    # - install_caddy
    # - install_awscli
    - security
