---
- name: Install node exporter
  import_tasks: install_node_exporter.yml
  when: node_exporter|default(false)|bool == true

- name: Install promtail
  import_tasks: install_promtail.yml
  when: promtail|default(false)|bool == true

- name: Install Zabbix
  import_tasks: install_zabbix.yml
